// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarsashaz.DAL.DbContexts;

namespace Tarsashaz.Migrations
{
    [DbContext(typeof(CondominiumDbContext))]
    [Migration("20200928092516_SeedUser")]
    partial class SeedUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tarsashaz.Models.Addresses.CondominiumAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<int>("Door")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId")
                        .IsUnique();

                    b.ToTable("CondominiumAddresses");
                });

            modelBuilder.Entity("Tarsashaz.Models.Addresses.FlatAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Door")
                        .HasColumnType("int");

                    b.Property<int>("FlatId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlatId")
                        .IsUnique();

                    b.ToTable("FlatAddresses");
                });

            modelBuilder.Entity("Tarsashaz.Models.Addresses.ProviderAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Door")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("ProviderAddresses");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Bill");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Bill");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.BillDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PayoffEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PayoffStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("BillDates");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNum")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("SenderId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Condominium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommonCharge")
                        .HasColumnType("int");

                    b.Property<int?>("CommonRepresentativeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonRepresentativeId");

                    b.ToTable("Condominiums");
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("UserId");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.FlatBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("FlatId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("FlatBalances");
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.FlatData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlatId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("FlatDatas");
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.BillPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique()
                        .HasFilter("[BillId] IS NOT NULL");

                    b.ToTable("BillPictures");
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.FlatPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlatDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlatDataId");

                    b.ToTable("FlatPictures");
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.ProblemPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemPictures");
                });

            modelBuilder.Entity("Tarsashaz.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lauferakos@gmail.com",
                            Name = "Akos",
                            Phone = "706477577",
                            Role = 0,
                            Token = "asdasdsadadasd"
                        },
                        new
                        {
                            Id = 2,
                            Email = "teszt1@gmail.com",
                            Name = "Teszt1",
                            Phone = "123546489",
                            Role = 1,
                            Token = "qweqwewqqweqeqe1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "teszt2@gmail.com",
                            Name = "Teszt2",
                            Phone = "123546489",
                            Role = 1,
                            Token = "qweqwewqqweqeqe2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "teszt3@gmail.com",
                            Name = "Teszt3",
                            Phone = "123546489",
                            Role = 1,
                            Token = "qweqwewqqweqeqe3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "teszt4@gmail.com",
                            Name = "Teszt4",
                            Phone = "123546489",
                            Role = 1,
                            Token = "qweqwewqqweqeqe4"
                        });
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.CondominiumBill", b =>
                {
                    b.HasBaseType("Tarsashaz.Models.Bills.Bill");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int");

                    b.Property<int?>("DestAddressId")
                        .HasColumnType("int");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("DestAddressId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("CondominiumBill");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.FlatBill", b =>
                {
                    b.HasBaseType("Tarsashaz.Models.Bills.Bill");

                    b.Property<int?>("DestAddressId")
                        .HasColumnName("FlatBill_DestAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("FlatId")
                        .HasColumnType("int");

                    b.HasIndex("DestAddressId");

                    b.HasIndex("FlatId");

                    b.HasIndex("UserId")
                        .HasName("IX_Bill_UserId1");

                    b.HasDiscriminator().HasValue("FlatBill");
                });

            modelBuilder.Entity("Tarsashaz.Models.Addresses.CondominiumAddress", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Condominium", "Condominium")
                        .WithOne("Address")
                        .HasForeignKey("Tarsashaz.Models.Addresses.CondominiumAddress", "CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Addresses.FlatAddress", b =>
                {
                    b.HasOne("Tarsashaz.Models.Flats.Flat", "Flat")
                        .WithOne("Address")
                        .HasForeignKey("Tarsashaz.Models.Addresses.FlatAddress", "FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Addresses.ProviderAddress", b =>
                {
                    b.HasOne("Tarsashaz.Models.Bills.Provider", "Provider")
                        .WithOne("Address")
                        .HasForeignKey("Tarsashaz.Models.Addresses.ProviderAddress", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.Bill", b =>
                {
                    b.HasOne("Tarsashaz.Models.Bills.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.BillDate", b =>
                {
                    b.HasOne("Tarsashaz.Models.Bills.Bill", "Bill")
                        .WithOne("BillDate")
                        .HasForeignKey("Tarsashaz.Models.Bills.BillDate", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Announcement", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Condominium", "Condominium")
                        .WithMany("Announcements")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarsashaz.Models.Users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Condominium", b =>
                {
                    b.HasOne("Tarsashaz.Models.Users.User", "CommonRepresentative")
                        .WithMany()
                        .HasForeignKey("CommonRepresentativeId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Condominiums.Problem", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Condominium", "Condominium")
                        .WithMany("Problems")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.Flat", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Condominium", "Condominium")
                        .WithMany("Flats")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarsashaz.Models.Users.User", "User")
                        .WithMany("Flats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.FlatBalance", b =>
                {
                    b.HasOne("Tarsashaz.Models.Flats.Flat", "Flat")
                        .WithMany("Balances")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Flats.FlatData", b =>
                {
                    b.HasOne("Tarsashaz.Models.Flats.Flat", "Flat")
                        .WithMany("FlatDatas")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.BillPicture", b =>
                {
                    b.HasOne("Tarsashaz.Models.Bills.Bill", "Bill")
                        .WithOne("Picture")
                        .HasForeignKey("Tarsashaz.Models.Pictures.BillPicture", "BillId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.FlatPicture", b =>
                {
                    b.HasOne("Tarsashaz.Models.Flats.FlatData", "FlatData")
                        .WithMany("Pics")
                        .HasForeignKey("FlatDataId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Pictures.ProblemPicture", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Problem", "Problem")
                        .WithMany("Pictures")
                        .HasForeignKey("ProblemId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.CondominiumBill", b =>
                {
                    b.HasOne("Tarsashaz.Models.Condominiums.Condominium", "Condominium")
                        .WithMany("Bills")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarsashaz.Models.Addresses.CondominiumAddress", "DestAddress")
                        .WithMany("Bills")
                        .HasForeignKey("DestAddressId");

                    b.HasOne("Tarsashaz.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Tarsashaz.Models.Bills.FlatBill", b =>
                {
                    b.HasOne("Tarsashaz.Models.Addresses.FlatAddress", "DestAddress")
                        .WithMany()
                        .HasForeignKey("DestAddressId");

                    b.HasOne("Tarsashaz.Models.Flats.Flat", "Flat")
                        .WithMany("Bills")
                        .HasForeignKey("FlatId");

                    b.HasOne("Tarsashaz.Models.Users.User", "User")
                        .WithMany("FlatBills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Bill_Users_UserId1");
                });
#pragma warning restore 612, 618
        }
    }
}
